    name: C++ Build

    on:
      push:
        branches: [ "main" ]
      pull_request:
        branches: [ "main" ]

    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install latest g++
          uses: rlalik/setup-cpp-compiler@v1.2
          with:
            compiler: latest

        - name: Build
          run: g++ -std=c++17 ./day2/security.cpp -o main

        - name: Run
          run: ./main
